spring:
  application:
    name: kafka

  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/auth?options=-c%20timezone=UTC
    username: user
    password: Omganesh2006
    driver-class-name: org.postgresql.Driver

  # JPA & Hibernate configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  # Kafka Configuration
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

jwt:
  secret-key: 2f5400352a42dd99c2953e4e6c60ce80d7f3856d7c680d8af2d92349e8f9133d
  expiration: 3600000 # 1 hour in milliseconds
